title = "EGATi Intranet"
baseURL = "https://intranet.egati.co.th/"
# baseURL = "https://easy.egati.co.th/intranet/"

languageCode = "en-us"
theme = "ars"

[params]

  
[menu]
 
# [[menu.header]]
#    weight = 1
#    name = "รวมช่องการเข้าถึงภายใน"
#      url = "Information"
  [[menu.header2]]
      weight = 1
      name = "เบอร์โทรติดต่อภายใน"
      url = "https://easy.egati.co.th/egaticontact/"
  [[menu.header2]]
      weight = 2
      name = "ข่าวสารและประชาสัมพันธ์"
      url = "https://info.egati.co.th/processwire_news/my_blog/"
#  [[menu.header]]
 #     name = "คณะกรรมการ"
  #    weight = 1
   #   url = "bord_sec"



